server:
  port: 8082

spring:
  application:
    nem: pra-cha-ms-plazoletapra-cha-ms-plazoleta

  datasource:
    url: jdbc:mysql://localhost:3306/BD_PLAZOLETA?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false

users:
  service:
    url: http://localhost:8081

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs
